package org.intellij.privacyHelper.codeInspection.utils;

import org.intellij.privacyHelper.codeInspection.personalDataAPIAnnotationUtils.*;
import org.intellij.privacyHelper.codeInspection.personalDataEntityTrackers.PersonalDataInCallerTargetVariableTracker;
import org.intellij.privacyHelper.codeInspection.personalDataEntityTrackers.PersonalDataInMethodCallParameterTargetVariableTracker;
import org.intellij.privacyHelper.codeInspection.personalDataEntityTrackers.ReturnValueTargetVariableTracker;

import static org.intellij.privacyHelper.codeInspection.utils.AccessType.*;

/**
 * Created by tianshi on 2/3/18.
 */
public class PersonalDataSinkAPIList {
    static SensitiveAPI[] sensitiveAPIs = {
            new TargetVariableInMethodCallParameterAPI("(volley) RequestQueue.add",
                    "com\\.android\\.volley\\.RequestQueue\\.add",
                    ".*",
                    new AndroidPermission[][]{},
                    new AndroidPermission[][]{}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0),false, true,
                    SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI("(apache) Request.Get",
                    "org\\.apache\\.http\\.client\\.fluent\\.Request\\.Get",
                    "org\\.apache\\.http\\.client\\.fluent\\.Request",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI("(apache) Request.Post",
                    "org\\.apache\\.http\\.client\\.fluent\\.Request\\.Post",
                    "org\\.apache\\.http\\.client\\.fluent\\.Request",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI("(apache) Request.Put",
                    "org\\.apache\\.http\\.client\\.fluent\\.Request\\.Put",
                    "org\\.apache\\.http\\.client\\.fluent\\.Request",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI("(apache) Request.Delete",
                    "org\\.apache\\.http\\.client\\.fluent\\.Request\\.Delete",
                    "org\\.apache\\.http\\.client\\.fluent\\.Request",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI("URLConnection.getOutputStream",
                    "java\\.net\\.URLConnection\\.getOutputStream",
                    ".*OutputStream",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI("(apache) HttpClient.execute",
                    "org\\.apache\\.http.*\\.client\\..*HttpClient\\.execute",
                    ".*Response",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI("(okhttp3) Request.Builder.url",
                    "okhttp3\\.Request\\.Builder\\.url",
                    "okhttp3\\.Request\\.Builder",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI("(okhttp3) Request.Builder.post",
                    "okhttp3\\.Request\\.Builder\\.post",
                    "okhttp3\\.Request\\.Builder",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI("(Cloud Storage for Firebase) StorageReference.putBytes",
                    "com\\.google\\.firebase\\.storage\\.StorageReference\\.putBytes",
                    "com\\.google\\.firebase\\.storage\\.UploadTask",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateCloudStorageSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    STORED_ON_CLOUD),
            new TargetVariableInMethodCallParameterAPI("(Cloud Storage for Firebase) StorageReference.putFile",
                    "com\\.google\\.firebase\\.storage\\.StorageReference\\.putFile",
                    "com\\.google\\.firebase\\.storage\\.UploadTask",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateCloudStorageSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    STORED_ON_CLOUD),
            new TargetVariableInMethodCallParameterAPI("(Cloud Storage for Firebase) StorageReference.putStream",
                    "com\\.google\\.firebase\\.storage\\.StorageReference\\.putStream",
                    "com\\.google\\.firebase\\.storage\\.UploadTask",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateCloudStorageSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    STORED_ON_CLOUD),
            new TargetVariableInMethodCallParameterAPI("(Firebase Cloud Firestore) CollectionReference.add",
                    "com\\.google\\.firebase\\.firestore\\.CollectionReference\\.add",
                    ".*",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateCloudStorageSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    STORED_ON_CLOUD),
            new TargetVariableInMethodCallParameterAPI("(Firebase Cloud Firestore) DocumentReference.set",
                    "com\\.google\\.firebase\\.firestore\\.DocumentReference\\.set",
                    ".*",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateCloudStorageSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    STORED_ON_CLOUD),
            new TargetVariableInMethodCallParameterAPI("(Firebase Cloud Firestore) DocumentReference.update",
                    "com\\.google\\.firebase\\.firestore\\.DocumentReference\\.update",
                    ".*",
                    new String []{".*Map<.*String,.*>"},
                    new String []{".*"},
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateCloudStorageSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    STORED_ON_CLOUD),
            new TargetVariableInMethodCallParameterAPI("(Firebase Cloud Firestore) DocumentReference.update",
                    "com\\.google\\.firebase\\.firestore\\.DocumentReference\\.update",
                    ".*",
                    new String []{".*ParsedUpdateData"},
                    new String []{".*"},
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateCloudStorageSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    STORED_ON_CLOUD),
            new TargetVariableInMethodCallParameterAPI("(Firebase Cloud Firestore) DocumentReference.update",
                    "com\\.google\\.firebase\\.firestore\\.DocumentReference\\.update",
                    ".*",
                    new String []{".*String"},
                    new String []{".*"},
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateCloudStorageSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(1), false, true,
                    STORED_ON_CLOUD),
            new TargetVariableInMethodCallParameterAPI("(Firebase Cloud Firestore) DocumentReference.update",
                    "com\\.google\\.firebase\\.firestore\\.DocumentReference\\.update",
                    ".*",
                    new String []{".*FieldPath"},
                    new String []{".*"},
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateCloudStorageSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(1), false, true,
                    STORED_ON_CLOUD),
            // FIXME: currently only requires annotation on the second parameter, should also support all other parameters.
            // see: public Task<Void> update(@NonNull String field, @Nullable Object value, Object... moreFieldsAndValues)
            // and public Task<Void> update(@NonNull FieldPath fieldPath, @Nullable Object value, Object... moreFieldsAndValues)

            new TargetVariableInMethodCallParameterAPI("(Firebase Realtime Database) DatabaseReference.setValue",
                    "com.google.firebase.database\\.DatabaseReference\\.setValue",
                    ".*",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateCloudStorageSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    STORED_ON_CLOUD),
            new TargetVariableInMethodCallParameterAPI("(Firebase Realtime Database) DatabaseReference.updateChildren",
                    "com.google.firebase.database\\.DatabaseReference\\.updateChildren",
                    ".*",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateCloudStorageSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    STORED_ON_CLOUD),

            new TargetVariableInMethodCallParameterAPI("RestTemplate.execute",
                    "org\\.springframework\\.web\\.client\\.RestTemplate\\.execute",
                    ".*",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI("RestTemplate.exchange",
                    "org\\.springframework\\.web\\.client\\.RestTemplate\\.exchange",
                    ".*",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI("RestTemplate.post",
                    "org\\.springframework\\.web\\.client\\.RestTemplate\\.post.*",
                    ".*",
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true,
                    SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI("Webview.loadUrl",
                    "android\\.webkit\\.WebView\\.loadUrl",
                    "void",
                    new String []{".*String"},
                    new String []{".*"},
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true, SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI("Webview.loadUrl",
                    "android\\.webkit\\.WebView\\.loadUrl",
                    "void",
                    new String []{".*String", ".*Map.*"},
                    new String []{".*", ".*"},
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true, SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI("Webview.loadUrl",
                    "android\\.webkit\\.WebView\\.loadUrl",
                    "void",
                    new String []{".*String", ".*Map.*"},
                    new String []{".*", ".*"},
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(1), false, true, SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI("Webview.postUrl",
                    "android\\.webkit\\.WebView\\.postUrl",
                    "void",
                    new String []{".*String", ".*byte.*"},
                    new String []{".*", ".*"},
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true, SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI("Webview.postUrl",
                    "android\\.webkit\\.WebView\\.postUrl",
                    "void",
                    new String []{".*String", ".*byte.*"},
                    new String []{".*", ".*"},
                    new AndroidPermission[][] {},
                    new AndroidPermission[][] {}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(1), false, true, SENT_OFF_DEVICE),
            new TargetVariableInCallerAPI("URL.openConnection",
                    "java\\.net\\.URL\\.openConnection",
                    ".*URLConnection",
                    new String[]{},
                    new String[]{},
                    new AndroidPermission[][]{},
                    new AndroidPermission[][]{}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInCallerTargetVariableTracker(), false, true, SENT_OFF_DEVICE
                    ),
            new TargetVariableInCallerAPI("URL.openConnection",
                    "java\\.net\\.URL\\.openConnection",
                    ".*URLConnection",
                    new String[]{".*Proxy"},
                    new String[]{".*"},
                    new AndroidPermission[][]{},
                    new AndroidPermission[][]{}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInCallerTargetVariableTracker(), false, true, SENT_OFF_DEVICE
            ),
            new TargetVariableInCallerAPI("URL.openStream",
                    "java\\.net\\.URL\\.openStream",
                    ".*InputStream",
                    new String[]{},
                    new String[]{},
                    new AndroidPermission[][]{},
                    new AndroidPermission[][]{}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInCallerTargetVariableTracker(), false, true, SENT_OFF_DEVICE
            ),
            new TargetVariableInCallerAPI("URL.getContent",
                    "java\\.net\\.URL\\.getContent",
                    ".*",
                    new String[]{},
                    new String[]{},
                    new AndroidPermission[][]{},
                    new AndroidPermission[][]{}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInCallerTargetVariableTracker(), false, true, SENT_OFF_DEVICE
            ),
            new TargetVariableInCallerAPI("URL.getContent",
                    "java\\.net\\.URL\\.getContent",
                    ".*",
                    new String[]{".*"},
                    new String[]{".*"},
                    new AndroidPermission[][]{},
                    new AndroidPermission[][]{}, false, null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new PersonalDataInCallerTargetVariableTracker(), false, true, SENT_OFF_DEVICE
            ),
            new TargetVariableInMethodCallParameterAPI(
                    "SmsManager.sendTextMessage",
                    "android\\.telephony\\.SmsManager\\.sendTextMessage",
                    "void",
                    new String[]{".*String", ".*String", ".*String", ".*PendingIntent", ".*PendingIntent"},
                    new String[]{".*", ".*", ".*", ".*", ".*"},
                    new AndroidPermission[][]{{AndroidPermission.SEND_SMS}},
                    new AndroidPermission[][]{},
                    false,
                    null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new ReturnValueTargetVariableTracker(),false, true, SENT_OFF_DEVICE
            ), // SmsManager.sendTextMessage(String destinationAddress, String scAddress, String text, PendingIntent sentIntent, PendingIntent deliveryIntent)
            new TargetVariableInMethodCallParameterAPI(
                    "SmsManager.sendDataMessage",
                    "android\\.telephony\\.SmsManager\\.sendDataMessage",
                    "void",
                    new String[]{".*String", ".*String", ".*short", ".*byte\\[\\]", ".*PendingIntent", ".*PendingIntent"},
                    new String[]{".*", ".*", ".*", ".*", ".*", ".*"},
                    new AndroidPermission[][]{{AndroidPermission.SEND_SMS}},
                    new AndroidPermission[][]{},
                    false,
                    null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new ReturnValueTargetVariableTracker(),false, true, SENT_OFF_DEVICE
            ), // SmsManager.sendDataMessage(String destinationAddress, String scAddress, short destinationPort, byte[] data, PendingIntent sentIntent, PendingIntent deliveryIntent)
            new TargetVariableInMethodCallParameterAPI(
                    "SmsManager.sendMultimediaMessage",
                    "android\\.telephony\\.SmsManager\\.sendMultimediaMessage",
                    "void",
                    new String[]{".*Context", ".*Uri", ".*String", ".*Bundle", ".*PendingIntent"},
                    new String[]{".*", ".*", ".*", ".*", ".*"},
                    new AndroidPermission[][]{}, //Does not use the SEND_SMS permission
                    new AndroidPermission[][]{},
                    false,
                    null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new ReturnValueTargetVariableTracker(),false, true, SENT_OFF_DEVICE
            ), // SmsManager.sendMultimediaMessage(Context context, Uri contentUri, String locationUrl, Bundle configOverrides, PendingIntent sentIntent)
            new TargetVariableInMethodCallParameterAPI(
                    "SmsManager.sendMultipartTextMessage",
                    "android\\.telephony\\.SmsManager\\.sendMultipartTextMessage",
                    "void",
                    new String[]{".*String", ".*String", ".*ArrayList<String>", ".*ArrayList<PendingIntent>", ".*ArrayList<PendingIntent>"},
                    new String[]{".*", ".*", ".*", ".*", ".*"},
                    new AndroidPermission[][]{{AndroidPermission.SEND_SMS}},
                    new AndroidPermission[][]{},
                    false,
                    null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new ReturnValueTargetVariableTracker(),false, true, SENT_OFF_DEVICE
            ), // SmsManager.sendMultipartTextMessage(String destinationAddress, String scAddress, ArrayList<String> parts, ArrayList<PendingIntent> sentIntents, ArrayList<PendingIntent> deliveryIntents)
            new TargetVariableInMethodCallParameterAPI(
                    "SmsManager.sendTextMessageWithoutPersisting",
                    "android\\.telephony\\.SmsManager\\.sendTextMessageWithoutPersisting",
                    "void",
                    new String[]{".*String", ".*String", ".*String", ".*PendingIntent", ".*PendingIntent"},
                    new String[]{".*", ".*", ".*", ".*", ".*"},
                    new AndroidPermission[][]{}, //Does not use the SEND_SMS permission
                    new AndroidPermission[][]{},
                    false,
                    null,
                    new CreateNetworkSinkAnnotationUtil(),
                    new ReturnValueTargetVariableTracker(),false, true, SENT_OFF_DEVICE
            ), // SmsManager.sendTextMessageWithoutPersisting(String destinationAddress, String scAddress, String text, PendingIntent sentIntent, PendingIntent deliveryIntent)

            new TargetVariableInMethodCallParameterAPI(
                    "OutputStream.write",
                    "java\\.io\\..*OutputStream\\.write",
                    "void",
                    new String[]{}, new String[]{},
                    new AndroidPermission[][]{},
                    new AndroidPermission[][]{}, false, null,
                    new CreateSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true, SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI(
                    "Writer.write",
                    "java\\.io\\..*Writer\\.write",
                    "void",
                    new String[]{}, new String[]{},
                    new AndroidPermission[][]{},
                    new AndroidPermission[][]{}, false, null,
                    new CreateSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true, SENT_OFF_DEVICE),
            new TargetVariableInMethodCallParameterAPI(
                    "Writer.append",
                    "java\\.io\\..*Writer\\.append",
                    ".*Writer",
                    new String[]{}, new String[]{},
                    new AndroidPermission[][]{},
                    new AndroidPermission[][]{}, false, null,
                    new CreateSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true, SENT_OFF_DEVICE),


            new TargetVariableInMethodCallParameterAPI("(Google Cloud Storage) Storage.create",
                    "com\\.google\\.cloud\\.storage\\.Storage\\.create",
                    ".*Blob",
                    new String[]{".*", ".*byte\\[\\]|.*InputStream"},
                    new String[]{".*", ".*"},
                    new AndroidPermission[][]{},
                    new AndroidPermission[][]{}, false, null,
                    new CreateCloudStorageSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(1), false, true, STORED_ON_CLOUD),

            new TargetVariableInMethodCallParameterAPI("(Google Cloud Storage) Storage.createFrom",
                    "com\\.google\\.cloud\\.storage\\.Storage\\.createFrom",
                    ".*Blob",
                    new AndroidPermission[][]{},
                    new AndroidPermission[][]{}, false, null,
                    new CreateCloudStorageSinkAnnotationUtil(),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(1), false, true, STORED_ON_CLOUD),

            new TargetVariableInMethodCallParameterAPI(
                    "setResult (send files to other apps)",
                    ".*setResult",
                    "void",
                    new String[]{".*", ".*Intent"},
                    new String[]{".*", ".*"},
                    new AndroidPermission[][]{},
                    new AndroidPermission[][]{}, false, null,
                    new ActivitySendFileAnnotationUtil(1),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(1), false, true, SHARE_ON_DEVICE),

            new TargetVariableInMethodCallParameterAPI(
                    "startActivity (send data to other apps)",
                    ".*startActivity",
                    "void",
                    new String[]{".*Intent"},
                    new String[]{".*"},
                    new AndroidPermission[][]{},
                    new AndroidPermission[][]{}, false, null,
                    new StartActivityToSendDataAnnotationUtil(0),
                    new PersonalDataInMethodCallParameterTargetVariableTracker(0), false, true, SHARE_ON_DEVICE),

    };

    static public SensitiveAPI[] getAPIList() {
        return sensitiveAPIs;
    }
}